libtenum: tenum::enum_helper< EnumType > Struct Template Reference
tenum::enum_helper< EnumType > Struct Template Reference
#include <helper.hpp>
Static Public Member Functions
static EnumType deserialize (::std::string const &value_in)
template<bool const IsDynamic, bool const IsBitField>
static EnumType deserialize_impl (::std::string const &value_in,::boost::integral_constant< bool, IsDynamic > const &is_dynamic,::boost::integral_constant< bool, IsBitField > const &is_bit_field)
static EnumType get_base_of (EnumType const value_in)
static inline::std::string serialize (EnumType const value_in)
template<bool const IsDynamic, bool const IsBitField>
static inline::std::string serialize_impl (EnumType const enum_value_in,::boost::integral_constant< bool, IsDynamic > const &is_dynamic,::boost::integral_constant< bool, IsBitField > const &is_bit_field)
Detailed Description
template<typename EnumType>
struct tenum::enum_helper< EnumType >
Todo:
comment.
Definition at line 40 of file helper.hpp.
Member Function Documentation
template<typename EnumType > static EnumType tenum::enum_helper< EnumType >::deserialize (::std::string const & value_in) [inline, static]
Todo:
comment.
Parameters:
value_in
Returns:
Definition at line 98 of file helper.hpp.
References tenum::enum_helper< EnumType >::deserialize_impl().
template<typename EnumType > template<bool const IsDynamic, bool const IsBitField> static EnumType tenum::enum_helper< EnumType >::deserialize_impl (::std::string const & value_in, ::boost::integral_constant< bool, IsDynamic > const & is_dynamic, ::boost::integral_constant< bool, IsBitField > const & is_bit_field) [inline, static]
Todo:
comment.
Parameters:
value_in
is_dynamic
is_bit_field
Returns:
Definition at line 74 of file helper.hpp.
Referenced by tenum::enum_helper< EnumType >::deserialize().
template<typename EnumType > static EnumType tenum::enum_helper< EnumType >::get_base_of (EnumType const value_in) [inline, static]
Todo:
comment.
Parameters:
value_in
Returns:
template<typename EnumType > static inline ::std::string tenum::enum_helper< EnumType >::serialize (EnumType const value_in) [inline, static]
Todo:
comment.
Parameters:
value_in
Returns:
Definition at line 89 of file helper.hpp.
References tenum::enum_helper< EnumType >::serialize_impl().
template<typename EnumType > template<bool const IsDynamic, bool const IsBitField> static inline ::std::string tenum::enum_helper< EnumType >::serialize_impl (EnumType const enum_value_in, ::boost::integral_constant< bool, IsDynamic > const & is_dynamic, ::boost::integral_constant< bool, IsBitField > const & is_bit_field) [inline, static]
Todo:
comment.
Parameters:
enum_value_in
is_dynamic
is_bit_field
Returns:
Definition at line 56 of file helper.hpp.
Referenced by tenum::enum_helper< EnumType >::serialize().
The documentation for this struct was generated from the following file:
include/tenum/detail/helper.hpp